### PR TITLE
adds codeowners

### PR DESCRIPTION
**Pull request by adamstrickland**

### CODE REVIEW

**Comment by jlambert121** [comment]
The `owners.json` file should probably be updated as well.

**Comment by adamstrickland** [comment]
> The `owners.json` file should probably be updated as well.

Actually, I'm wondering about that...  This is an open-source gem; seems to me that with a  `CODEOWNERS`, maybe we should remove `owners.json`...  Thoughts?

**Comment by jlambert121** [comment]
It still needs it so goro can update the CCI yaml file.

**Comment by adamstrickland** [comment]
Are the tests expected to pass?  Seems kinda broken-widows-y

**Comment by jlambert121** [comment]
"supposed to" - I'd assume yes.  Last time they did, not sure.  The travis tests look to be using old versions of ruby at a minimum.

**Comment by adamstrickland** [comment]
@jlambert121 so.... if i'm reading this right, it appears that no builds have passed specs in [over a year](https://github.com/stitchfix/pwwka/pulls?utf8=%E2%9C%93&q=is%3Apr).  However, up until now there have been 6 checks in the repo; 4 for circle and 2 for travis.  It looks like the circle checks have been removed?  I don't seem to have permissions to see what's up there.

**Pull request merged**
