### PR TITLE
Dependent gem updates.

### PR DESCRIPTION
**Pull request by billeisenhauer**
Specs passed.

### CODE REVIEW

**Comment by jstrait** [comment]
@billeisenhauer I think this is good to merge, unless @nickflux disagrees (asking because I'm not sure exactly the process for changing pwwka).

**Comment by billeisenhauer** [comment]
@nickflux will be out this week on holiday, so will check back next week.




*Bill Eisenhauer, Lead Engineer*
Stitch Fix | your style. delivered.
816 Congress Ave., Suite. 900
Austin, TX 78701
E: bill@stitchfix.com
P: 972-951-3759 <//972-951-3759>
Are you bright, kind and goal oriented? We are hiring people just like
you! Check
us out <https://www.stitchfix.com/careers>.

**Comment by davetron5000** [comment]
This can be merged—the contents of `Gemfile.lock` have zero affect on users of this gem, so if the tests are passing, it's good.  The update is to make sure latest versions of dependencies don't break the gem itself.

**Comment by billeisenhauer** [comment]
I do not have merge rights (member vs. owner), can someone do the honors?

**Comment by davetron5000** [comment]
Hmm, you were not in Owners.  Now you are, and should be able to merge.

**Pull request merged**
