### PR TITLE
Gem and ruby update for september

### PR DESCRIPTION
**Pull request by galori**

### CODE REVIEW

**Comment by simeonwillbanks** [comment]
@galori  Please add `2.2.2` to the [`.travis.yml`](https://github.com/stitchfix/pwwka/blob/83878f750260939db6211b6cfe22a7d2c26633a1/.travis.yml).  Thanks!

**Comment by galori** [comment]
@simeonwillbanks roger that

**Comment by simeonwillbanks** [comment]
:ship:

**Comment by davetron5000** [comment]
closing as old

**Pull request closed without merging**
